.TH targetd 8
.SH NAME
.B targetd
.SH DESCRIPTION
.B targetd
is a service to allow the remote configuration of block device volumes and
file systems within a pool, as well as exporting volumes to other hosts via iSCSI.
Configured remote file systems will be made available via NFS/CIFS.
.SH USAGE
Run
.B targetd
as root.
.SH CONFIGURATION
.B targetd
uses
.B /etc/target/targetd.yaml
for configuration. It is in YAML format.
.B targetd
currently uses scalar values and collection values, see example for details.
.SS CONFIGURATION FILE SETTINGS
.B pools:
.br
Sets the LVM Volume Group or file system mount point(s) that
.B targetd
will use to allocate volumes or file system from. Defaults to
.br
.B "pools:"
.br
.B "  vg-targetd: {type: block, uuid: null}"
.br
.P
.B targetd
currently supports arbitrary number of lvm volume groups and btrfs mount points.
.P
.B user
.br
.B password
.br
Sets the username and password required to use the remote
API. Defaults to 
.B admin
and
.BR targetd ,
respectively.
.P
.B target_name
.br
Sets the iSCSI target name that
.B targetd
will use. Default is
.BR iqn.2003-01.org.linux-iscsi.<hostname>:targetd .
.P
.B ssl
.br
.B ssl_key
.br
.B ssl_cert
.br
Settings for enabling SSL/TLS encryption.
.B ssl
defaults to
.BR off .
If enabled, it will default to looking for key and cert files named
.B targetd_key.pem
and
.BR targetd_cert.pem
in
.BR /etc/target .
These paths may also be specified, using the
.B ssl_key
and
.B ssl_cert
config settings.
.P
Key and self-signed cert may be generated using openssl:
.P
.B openssl genrsa -out targetd_key.pem 2048
.br
.B openssl req -new -x509 -key targetd_key.pem -out targetd_cert.pem -days 9999
.SH FILES
.B /etc/target/targetd.yaml
.SH SEE ALSO
The remote API is defined at
.br
<https://github.com/agrover/targetd/blob/master/API.md>.

targetcli(8), lvm(8), lsmcli(8)
.SH AUTHOR
Written by Andy Grover <agrover@redhat.com>.
.SH REPORTING BUGS
Report bugs via <target-devel@vger.kernel.org>
.br
or <https://github.com/agrover/targetd/issues>
